#OBJS specifies which files to compile as part of the project
OBJS = simulation.cpp ../alib/doormgr.cpp ../alib/rseed.cpp ../alib/utils.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = simulation

#This is the target that compiles our executable
all : $(OBJS)
	g++ $(OBJS) -o $(OBJ_NAME)